cnblog/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.views.static import serve
from django.urls import path, re_path
from blog import views
from cnblog import settings

urlpatterns = [
    path('admin/', admin.site.urls),  # 后台数据管理
    re_path('^$', views.get_index),  # index页面
    re_path('^test', views.test),  # 自定义测试页面
    re_path('^diggit', views.diggit),  # 赞、反对视图
    re_path('^media/(?P<path>.*)/$', serve, {'document_root': settings.MEDIA_ROOT}),  # media接口
    re_path('^register/(?P<protocol>protocol/)?$', views.register),  # 注册视图
    re_path('^login/', views.login),  # 登录视图
    re_path('^logout/', views.logout),  # 注销视图
    re_path('^comment/', views.comment),  # 评论视图
    re_path('^get-comment-tree/', views.get_comment_tree),  # 评论树
    re_path('^cnblog-backend/$', views.manage_backend),  # 后台管理
    re_path('^cnblog-backend/add-article/', views.add_article),  # 添加文章
    re_path('^upload/', views.upload),  # 文本编辑器上传
    url(regex=r'^pc-geetest/register', view=views.pcgetcaptcha, name='pcgetcaptcha'),  # 滑动验证码第一次校验
    re_path('^(?P<sitename>\w{4,})$', views.get_homesite),  # 个人站点视图
    re_path('^(?P<sitename>\w{4,})/(?P<condition>tag|category|archive|)/(?P<param>.+)', views.get_homesite),
    # 标签、分类、档案请求
    re_path('^(?P<sitename>\w{4,})/(?P<article>article)/(?P<article_id>\d+)', views.get_article_detail),  # 文章详情

    # markdown
    re_path('^markdown/', views.simplemde),

    re_path('^', views.get_404_page),  # 404

]

blog/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


# 用户认证组件的大前提是使用auth_user表
# 如果我们想在auth_user表的字段上进行扩展，那么我们需要继承AbstractUser
# 需要注意，数据库迁移后，是没有auth_user表的
# 也就是如果我们自己没有定义一个类并且继承AbstractUser，才会有auth_user
class UserInfo(AbstractUser):
    """
    用户信息
    """

    nid = models.AutoField(primary_key=True)
    telephone = models.CharField(max_length=11, null=True, unique=True)
    # SQL疑惑点：
    # 如果nid为主键。但是telephone设置为not null & unique，会不会有两个主键呢？
    # 解答：
    # 首先，innodb引擎不可能有两个主键，
    # nid是主键（必须的），telephone是not null & unique两个约束，仅此而已。
    # 如果在not null & unique之前有主键了，那么此字段不会转成主键
    # 如果之前不存在主键，那么会转成主键
    avatar = models.FileField(upload_to='avatars/', default='avatars/default.png')
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    blog = models.OneToOneField(to='Blog', to_field='nid', null=True, on_delete=models.CASCADE)
    # 一个用户只能有一个个人博客站点，相反，一个个人博客站点也只能属于一个人

    def __str__(self):
        return self.username


class Blog(models.Model):
    """
    博客信息
    """

    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='个人博客标题', max_length=64)
    site_name = models.CharField(verbose_name='站点名称', max_length=64)
    theme = models.CharField(verbose_name='博客主题', max_length=32)

    def __str__(self):
        return self.title


class Category(models.Model):
    """
    博主个人文章分类表
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='分类标题', max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid', on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Tag(models.Model):
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='标签名称', max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid', on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Article(models.Model):
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=50, verbose_name='文章标题')
    desc = models.CharField(max_length=255, verbose_name='文章描述')
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    content = models.TextField()

    comment_count = models.IntegerField(default=0)
    up_count = models.IntegerField(default=0)
    down_count = models.IntegerField(default=0)

    user = models.ForeignKey(verbose_name='作者', to='UserInfo', to_field='nid', on_delete=models.CASCADE)
    category = models.ForeignKey(to='Category', to_field='nid', null=True, on_delete=models.CASCADE)
    tags = models.ManyToManyField(
        to='Tag',
        through='Article2Tag',
        through_fields=('article', 'tag'),
    )

    def __str__(self):
        return self.title


class Article2Tag(models.Model):
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(verbose_name='文章', to='Article', to_field='nid', on_delete=models.CASCADE)
    tag = models.ForeignKey(verbose_name='标签', to='Tag', to_field='nid', on_delete=models.CASCADE)

    class Meta:
        unique_together = [
            ('article', 'tag'),
        ]

    def __str__(self):
        v = self.article.title + '---' + self.tag.title
        return v


class ArticleUpDown(models.Model):
    nid = models.AutoField(primary_key=True)
    user = models.ForeignKey('UserInfo', null=True, on_delete=models.CASCADE)
    article = models.ForeignKey('Article', null=True, on_delete=models.CASCADE)
    is_up = models.BooleanField(default=True)

    class Meta:
        unique_together = [
            ('article', 'user'),
        ]


class Comment(models.Model):
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(verbose_name='评论文章', to='Article', to_field='nid', on_delete=models.CASCADE)
    user = models.ForeignKey(verbose_name='评论者', to='UserInfo', to_field='nid', on_delete=models.CASCADE)
    content = models.CharField(verbose_name='评论内容', max_length=255)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    parent_comment = models.ForeignKey('self', null=True, on_delete=models.CASCADE)  # 自关联
    # parent_comment = models.ForeignKey('comment', null=True, on_delete=models.CASCADE)  # 这种写法是一样的

    def __str__(self):
        return self.content

blog/views.py
# 内置模块
import os
import json
import threading
# 第三方模块
from django.shortcuts import render, HttpResponse, redirect
from django.contrib import auth
from django.http import JsonResponse
from django.db.models import Count, F
from django.db.models.functions import TruncMonth
from django.db import transaction
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required
# from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .geetest import GeetestLib
from bs4 import BeautifulSoup
# 自制模块
from .models import UserInfo, Article, Category, Tag, ArticleUpDown, Comment, Blog
from .myform import UserForm
from .utils.check_code import get_check_code
from cnblog import settings

# Create your views here.

pc_geetest_id = "b46d1900d0a894591916ea94ea91bd2c"  # 滑动验证码id
pc_geetest_key = "36fc3fe98530eea08dfc6ce76e3d24c4"  # 滑动验证码key


def get_index(request):
    """
    index页面  http://127.0.0.1:8080/
    :param request: 请求体
    :return:
    """
    article_ls = Article.objects.all()
    return render(request=request, template_name='blog/index.html', context=locals())


def register(request, protocol):
    """
    register页面  http://127.0.0.1:8080/register/
                 http://127.0.0.1:8080/register/protocol/
    :param request:
    :return:

    extra points:
    # print(protocol)  # None，如果没有匹配的，为None
    """
    if request.method == 'POST':  # is_ajax()
        form = UserForm(data=request.POST)
        errors_response = dict(status=False)
        if not form.is_valid():
            global_errors = form.errors.get('__all__')
            for key in form.errors:  # 拿到所有的错误信息
                if key == '__all__':
                    continue
                errors_response[key] = form.errors.get(key)
            if global_errors:
                errors_response['confirmpwd'] = global_errors[0]
            return JsonResponse(data=errors_response)
        else:
            # 注册用户
            loginname = request.POST.get('loginname')
            nickname = request.POST.get('nickname')
            pwd = request.POST.get('pwd')
            tel = request.POST.get('tel')
            email = request.POST.get('email')
            avatar_obj = request.FILES.get('file')
            blog = Blog.objects.create(title=nickname, site_name=loginname, theme=f'{loginname}.css')
            extra_fields = dict()
            if avatar_obj:
                extra_fields['avatar'] = avatar_obj  # avatar字段必须接受一个文件对象
                # Django做的事情
                # 会把文件下载到avatar字段upload_to参数指定的值的位置，如果文件夹不存在，自动创建；avatar字段存放的是文件的相对路径
                # 如果没有指定upload_to，则会把文件下载到项目根目录下

                # 如果配置了media
                # 那么会把文件下载到media_root对应的文件夹中
            new_user = UserInfo.objects.create_user(
                username=loginname,
                password=pwd,
                telephone=tel,
                email=email,
                blog=blog,
                **extra_fields
            )
            new_user.save()
            errors_response['status'] = True
            errors_response['msg'] = '/login/'
            return JsonResponse(data=errors_response)
    else:
        form = UserForm(data=None)
        if protocol:
            return render(request=request, template_name='blog/register/protocol.html', context={})
        return render(request=request, template_name='blog/register.html', context=locals())


def login(request):
    """
    login页面  http://127.0.0.1:8080/login/
              http://127.0.0.1:8080/login/get-check-code/
    :param request:
    :return:
    """
    if request.method == 'POST':
        gt = GeetestLib(captcha_id=pc_geetest_id, private_key=pc_geetest_key)
        challenge = request.POST.get(gt.FN_CHALLENGE, '')
        validate = request.POST.get(gt.FN_VALIDATE, '')
        seccode = request.POST.get(gt.FN_SECCODE, '')
        status = request.session[gt.GT_STATUS_SESSION_KEY]
        user_id = request.session["user_id"]
        login_name = request.POST.get('loginName')
        password = request.POST.get('password')
        check_code = request.POST.get('checkCode')
        response = {'user': None, 'status': None, 'check_code_status': None, 'auth_status': None, 'msg': None}

        if status:
            result = gt.success_validate(challenge, validate, seccode, user_id)
        else:
            result = gt.failback_validate(challenge, validate, seccode)

        if result:
            response['status'] = True
            # 首先校验验证码
            if check_code.upper() != request.session['cur_check_code'].upper():
                response['msg'] = '验证码错误'
                response['check_code_status'] = False
                return JsonResponse(data=response)
            else:
                response['check_code_status'] = True
                user = auth.authenticate(username=login_name, password=password)
                if not user:
                    response['msg'] = '&lowast;&nbsp;用户名或密码错误'
                    response['auth_status'] = False
                    return JsonResponse(data=response)
                else:
                    auth.login(request=request, user=user)
                    response['user'] = login_name
                    response['msg'] = request.GET.get('next', '/')
                    response['auth_status'] = True
                    return JsonResponse(data=response)  # 自动序列化和反序列化
        else:
            response['status'] = False
            response['msg'] = '/get-404-page/'
            return JsonResponse(data=response)
    else:
        # http://127.0.0.1:8080/login/get-check-code/
        path = os.path.basename(os.path.dirname(request.path))
        if path == 'get-check-code':
            img_data = get_check_code(request=request)
            return HttpResponse(content=img_data)
        print(2)
        # login页面  http://127.0.0.1:8080/login/
        return render(request=request, template_name='blog/login.html', context={})


def pcgetcaptcha(request):
    """
    滑动验证码第一次校验
    :param request:
    :return:
    """
    user_id = 'geetest'
    gt = GeetestLib(captcha_id=pc_geetest_id, private_key=pc_geetest_key)
    status = gt.pre_process(user_id=user_id)
    request.session[gt.GT_STATUS_SESSION_KEY] = status
    request.session['user_id'] = user_id
    response_str = gt.get_response_str()
    return HttpResponse(content=response_str)


def get_404_page(request):
    """
    404page
    :param request:
    :return:
    """
    return render(request=request, template_name='blog/page404.html', context={})


def logout(request):
    """
    用户注销
    :param request:
    :return:
    """
    auth.logout(request=request)
    return redirect(to='/')


def get_homesite(request, sitename, **kwargs):
    """
    个人站点视图
    :param request:
    :param sitename:
    :param kwargs:
    :return:
    """
    # query_set = get_classification_data(sitename=sitename)
    # user = query_set.get('user')
    user = UserInfo.objects.all().filter(username=sitename).first()

    # 判断用户是否存在
    if not user:
        return get_404_page(request=request)

    # 获取当前站点对象
    # blog = user.blog
    # 获取当前用户或者当前站点对应的所有文章
    article_ls = Article.objects.all().filter(user=user)
    if kwargs:
        if kwargs['condition'] == 'tag':
            article_ls = article_ls.filter(tags__title=kwargs['param'])
        elif kwargs['condition'] == 'category':
            article_ls = article_ls.filter(category__title=kwargs['param'])
        else:
            year, month = kwargs['param'].split(sep='-')
            article_ls = article_ls.filter(create_time__year=year, create_time__month=month)
    # query_set['article_ls'] = article_ls
    # 获取当前用户或者站点对应的分类以及文章数
    # cate_ls = Category.objects.all().filter(blog=blog).values('pk').annotate(c=Count('article__category')).values('title', 'c')

    # 获取当前用户或者站点对应的标签以及文章数
    # tag_ls = Tag.objects.all().filter(blog=blog).values('pk').annotate(c=Count('article__pk')).values('title', 'c')  # Count('article') == Count('article__pk')等字段

    # 获取月份
    # 方式一
    # date_ls = Article.objects.all().filter(user=user).extra(select={'y_m': 'date_format(create_time, "%%Y-%%m")'}).values('y_m').annotate(c=Count('nid')).values('y_m', 'c')
    # extra会在原表的基础上新增一个字段
    # print(date_ls)

    # 方式二
    # date_ls = Article.objects.\
    #     all().\
    #     filter(user=user).\
    #     annotate(month=TruncMonth('create_time')).\
    #     values('month').\
    #     annotate(c=Count('nid')).values('month', 'c')
    return render(request=request, template_name='blog/homesite.html', context=locals())


def get_classification_data(sitename):
    user = UserInfo.objects.all().filter(username=sitename).first()

    blog = user.blog

    cate_ls = Category.objects.all().filter(blog=blog).values('pk').annotate(c=Count('article__category')).values(
        'title', 'c')

    tag_ls = Tag.objects.all().filter(blog=blog).values('pk').annotate(c=Count('article__pk')).values('title',
                                                                                                      'c')  # Count('article') == Count('article__pk')等字段

    date_ls = Article.objects. \
        all(). \
        filter(user=user). \
        annotate(month=TruncMonth('create_time')). \
        values('month'). \
        annotate(c=Count('nid')).values('month', 'c')
    return dict(user=user, blog=blog, cate_ls=cate_ls, tag_ls=tag_ls, date_ls=date_ls)


def get_article_detail(request, sitename, article, article_id):
    """
    文章详情页
    :param request: 请求体
    :param sitename: 站点名
    :param article: 文章固定格式字符串
    :param article_id: 文章id
    :return:
    """
    user = UserInfo.objects.all().filter(username=sitename).first()
    article_obj = Article.objects.all().get(nid=article_id)
    comment_ls = Comment.objects.all().filter(article_id=article_id)
    return render(request=request, template_name='blog/articledetail.html', context=locals())


def test(request):
    """
    测试视图
    :param request:
    :return:
    """

templates/blog/articledetail.html
{% extends 'blog/base.html' %}

{% block title %}
    <title>{{ user.username }} - 博客园</title>
{% endblock title %}

{% block content %}
    {% csrf_token %}
    <span id="id_article" class="invisible">{{ article_obj.pk }}</span>
    <div id="id_container_1" class="container">
        <h3 class="text-center text-success">{{ article_obj.title }}</h3>
        {% autoescape off %}
            {{ article_obj.content|safe }}
        {% endautoescape %}
        <div id="div_digg">
            <div class="diggit digg-action">
                <span class="diggnum" id="digg_count">{{ article_obj.up_count }}</span>
            </div>
            <div class="buryit digg-action">
                <span class="burynum" id="bury_count">{{ article_obj.down_count }}</span>
            </div>
            <div class="clear"></div>
            <div class="diggword" id="digg_tips"></div>
        </div>
    </div>

    <div class="clearfix"></div>

{#    评论树#}
    <div class="container well">
        <p class="feedback_area_title lead" id="id_comment_tree_title">评论树</p>
        <div class="comment-tree" id="id_comment_tree">

        </div>
    </div>

{#    评论列表#}
    <div class="container well">
        <div class="feedback_area_title lead">评论列表</div>
        <div class="list-group" id="id_list_group">
          {% for each_comment in comment_ls %}
            <button type="button" class="list-group-item" data-level="{{ forloop.counter }}">
                <a href="#"># {{ forloop.counter }}楼</a>&nbsp;&nbsp;
                <span>{{ each_comment.create_time|date:"Y-m-d H:i" }}</span>
                <a href="/{{ each_comment.user.username }}">{{ each_comment.user.username }}</a>
                <a title="发送站内短消息" class="sendMsg2This">&nbsp;</a>
                <a class="pull-right class-reply" data-username="{{ each_comment.user.username }}" data-commentId="{{ each_comment.pk }}">回复</a>
                {% if each_comment.parent_comment_id %}
                    <span class="help-block">@&nbsp;{{ each_comment.parent_comment.user.username }}: {{ each_comment.parent_comment.content }}</span>
                {% endif %}
                <span class="help-block">{{ each_comment.content }}</span>
            </button>
          {% endfor %}
        </div>
    </div>

    {% if request.user.is_authenticated %}
    <div class="container well">
        <div id="id_comment_title">发表评论</div>
        <p>
            昵称：
            <label>
                <input type="text" id="tbCommentAuthor" class="author" disabled="disabled" size="50" value="{{ request.user.username }}">
            </label>
        </p>
        <div class="commentbox_title">
            <div class="commentbox_title_left">评论内容：</div>
        </div>
        <div class="clearfix"></div>
        <div class="commentbox_cotent">
            <label>
                <textarea id="tbCommentBody" class="comment_textarea"></textarea>
            </label>
        </div>
        <div id="div_feedbak">
            <span class="invisible" id="id_feedback">感谢您的回复:)</span>
            <button id="id_btn_submit" class="btn btn-default pull-right" type="button">提交</button>
        </div>
    </div>
    {% else %}
        <div id="comment_form_container">
            <div class="login_tips">
                注册用户登录后才能发表评论，请
                <a rel="nofollow" href="/login/" class="underline">登录</a>
                或
                <a rel="nofollow" href="/register/" class="underline">注册</a>，
                <a href="/">访问</a>网站首页。
            </div>
        </div>
    {% endif %}
{% endblock content %}

{% block script %}
    <script type="text/javascript" src="/static/blog/js/articledetail.js"></script>
{% endblock script %}

templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
        <title>博客园 - 代码改变世界</title>
    {% endblock title%}
    <link rel="icon" href="/static/blog/img/register_dir/favicon.ico" type="image/x-icon"/>
    <link rel="stylesheet" type="text/css" href="/static/public/bootstrap3.3.7/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="/static/blog/css/base.css" />
    <link rel="stylesheet" type="text/css" href="/static/blog/css/classification.css" />
    <link rel="stylesheet" type="text/css" href="/static/blog/css/homesite.css" />
    <link rel="stylesheet" type="text/css" href="/static/blog/css/articledetail.css" />
    <script type="text/javascript" src="/static/public/jquery/jquery-3.4.0.js"></script>
    <script type="text/javascript" src="/static/public/bootstrap3.3.7/js/bootstrap.js"></script>
</head>
<body>
<div id="id_top_banner">
    <nav id="id_top_banner_nav" class="navbar navbar-default navbar-inverse">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div id="id_navbar_header" class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" id="id_navbar_brand" href="/{{ user.username }}">
                    <span>{{ user.blog.title }}</span>
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul id="id_ul" class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="/">博客园</a>
                    </li>
                    <li>
                        <a href="/">首页</a>
                    </li>
                    <li>
                        <a href="#">新随笔</a>
                    </li>
                    <li>
                        <a href="#">联系</a>
                    </li>
                    <li>
                        <a href="#">订阅</a>
                    </li>
                    <li>
                        <a href="/cnblog-backend/">管理</a>
                    </li>
                </ul>

            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
</div>

<div id="id_container_fluid" class="container-fluid">
    <div class="row">
        <div class="col-md-2 sidebar">
            {% load mytags %}
            {% get_classification_style sitename %}
        </div>

        <div class="col-md-10 content">
            {% block content %}

            {% endblock content%}

        </div>
    </div>
</div>

{% block script %}

{% endblock script %}
</body>
</html>

templates/blog/classification.html
<div class="calendar">
    <img id="id_img_rounded" class="img-rounded" src="/static/blog/img/homesite_dir/calendar.png" alt="日历" />
</div>

<div class="tags">
    <div class="panel panel-default">
        <div class="panel-heading" id="id_tags_panel_heading">
            <p>
                <b>
                    <span class="lead">我的标签</span>
                </b>
            </p>
        </div>
        <div class="list-group">
            {% for each_tag in tag_ls %}
                <a href="/{{ user.username }}/tag/{{ each_tag.title }}" class="list-group-item class-list-group-item">
                    <span class="badge">{{ each_tag.c }}</span>
                    {{ each_tag.title }}
                </a>
            {% endfor %}
        </div>
    </div>
</div>

<div class="categorys">
    <div class="panel panel-default">
        <div class="panel-heading" id="id_categorys_panel_heading">
            <p>
                <b>
                    <span class="lead">随笔分类</span>
                </b>
            </p>
        </div>
        <div class="list-group">
            {% for each_cate in cate_ls %}
                <a href="/{{ user.username }}/category/{{ each_cate.title }}" class="list-group-item class-list-group-item">
                    <span class="badge">{{ each_cate.c }}</span>
                    {{ each_cate.title }}
                </a>
            {% endfor %}
        </div>
    </div>
</div>

<div class="archives">
    <div class="panel panel-default">
        <div class="panel-heading" id="id_archives_panel_heading">
            <p>
                <b>
                    <span class="lead">随笔档案</span>
                </b>
            </p>
        </div>
        <div class="list-group">
            {% for each_date in date_ls %}
                <a href="/{{ user.username }}/archive/{{ each_date.month|date:'Y-m' }}" class="list-group-item class-list-group-item">
                    <span class="badge">{{ each_date.c }}</span>
                    {{ each_date.month|date:"Y年m日" }}
                </a>
            {% endfor %}
        </div>
    </div>
</div>

templates/blog/homesite.html
{% extends 'blog/base.html' %}

{% block title %}
    <title>{{ user.username }} - 博客园</title>
{% endblock title%}

{% block content %}
    {% for each_article in article_ls %}
        <div class="container">
            <div class="alert {% cycle 'alert-success' 'alert-info' 'alert-warning' 'alert-danger' %} alert-dismissible"
                 role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <div class="media">

                    <div class="media-body class-article-body">
                        <h4 class="media-heading class-article-heading">
                            <a href="/{{ user.username }}/article/{{ each_article.pk }}" class="alert-link">
                                {{ each_article.title }}
                            </a>
                        </h4>
                        <p class="small class-article-desc">
                            {{ each_article.desc }}
                            <footer class="small class-article-footer pull-right">
                                    <span>
                                        posted
                                    </span>
                                <span>
                                        &nbsp;@&nbsp;
                                    </span>
                                <span>
                                        {{ each_article.create_time|date:"Y-m-d H:i:s" }}
                                    </span>
                                <span class="glyphicon glyphicon-comment"></span>
                                <span>
                                        评论({{ each_article.comment_count }})
                                    </span>
                                <span class="glyphicon glyphicon-thumbs-up"></span>
                                <span>
                                        点赞({{ each_article.up_count }})
                                    </span>
                            </footer>
                    </div>
                </div>

            </div>
        </div>
    {% endfor %}
{% endblock %}

templates/blog/page404.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Error_404_资源不存在</title>
    <link rel="icon" href="/static/blog/img/register_dir/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" type="text/css" href="/static/blog/css/page404.css" />
</head>

<body id="id_body">
<div class="whole">
    <img src="/static/blog/img/page404_dir/back.jpg" alt="back.jpg" />
    <div class="mask"></div>
</div>
<div class="b">
    <img src="/static/blog/img/page404_dir/404.png" class="center" alt="404.png" />
    <p>
        暂时未能找到您查找的页面<br>
        可能输入的网址错误或此页面不存在<br>
        <span id="num"></span>秒后自动跳转到主页
    </p>
</div>

<script type="text/javascript" src="/static/blog/js/page404.js"></script>
</body>
</html>

templates/blog/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{ request.user.blog.title }}
{# 实验后的总结：#}
{# 首先1. request在一个视图函数中，是全局对象，不用传，也可以使用 #}
{# 2. auth.login()之后，request.user = user，这个user在所有的视图函数中都可以使用 #}
{# 3. 而且无需使用request引导，可以单独使用#}
</body>
</html>